<a href="https://colab.research.google.com/github/AshOne91/PLAYDATA-COURSE/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%9D%B4%ED%95%B4%EC%99%80_%EC%A4%80%EB%B9%84(%ED%83%90%EC%83%89%2C%ED%92%88%EC%A7%88%EA%B2%80%ED%86%A0%2C%EC%A0%95%EC%A0%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

판다스
```
엑셀처럼 데이터를 다룰수 있는 작은 프레임웍
시리즈
  1차원 배열, 명시적으로 인덱스를 가지는 구조
데이터 프레임
  2차원 배열
```

In [ ]:
import pandas as pd
import numpy as np
import random

# 리스트로 시리즈를 생성
list_1 = random.sample(range(1, 100), 3)
print(f'리스트 : {list_1}')
s1 = pd.Series(list_1)
print(f'시리즈 -------- \n {s1}')

리스트 : [71, 55, 29]
시리즈 --------
 0    71
1    55
2    29
dtype: int64

In [ ]:
# 딕셔너리로 시리즈를 생성
dict_1 = {'a':1, 'b':2, 'c':3}
print(f'딕셔너리 : {dict_1}')
s2 = pd.Series(dict_1)
print(f'시리즈 -------- \n {s2}')

딕셔너리 : {'a': 1, 'b': 2, 'c': 3}
시리즈 --------
 a    1
b    2
c    3
dtype: int64

In [ ]:
# 커스텀 인덱스
s3 = pd.Series([100, 200, 300], index=['apple', 'grap', 'banana'])
print(s3)

apple     100
grap      200
banana    300
dtype: int64

In [ ]:
# deprecated --> 곧 사라질 기능으로
# 원소 선택
# print(s3[0])
print(s3['apple'])
print(s1[0])

100
71

In [ ]:
# 슬라이싱  정수는 start : end-1
# 슬라이싱  문자열은 start : end
print(s3['apple':'banana'])
print(s1[0:2])

apple     100
grap      200
banana    300
dtype: int64
0    71
1    55
dtype: int64

In [ ]:
s3

apple     100
grap      200
banana    300
dtype: int64

판다스
```
시리즈 들의 집합
딕셔너리, 리스트, 넘파이 배열 등으로 생성가능
csv 파일이나 text, xlsx 등의 데이터를 판다스 객체로 생성
```

In [ ]:
# 데이터 프레임 만들기
# 딕셔너리 구조
data = {
    'name': ['a','b','c','d','e'],
    'age' : [10,20,30,20,10]
}
df = pd.DataFrame(data)
print(df)
df

  name  age
0    a   10
1    b   20
2    c   30
3    d   20
4    e   10

  name  age
0    a   10
1    b   20
2    c   30
3    d   20
4    e   10

In [ ]:
# 인덱스(행) 컬럼(열) 변경
df.index = ['a',' b','c','d','e']
df.columns = ['이름', '나이']
df

   이름  나이
a   a  10
 b  b  20
c   c  30
d   d  20
e   e  10

In [ ]:
# 삭제
# df = df.drop('a')
df.drop('a',inplace=True)

In [ ]:
# 여러개의 행을 삭제
# df =  df.drop(['b','c'])  # axis=0 기본값
# df.drop(['b','c'], inplace=True)  # axis=0 기본값
# df.drop(['b','c'], axis=0, inplace=True)

In [ ]:
# 열을 삭제
# df =  df.drop('나이',axis=1)
# df =  df.drop('나이',axis=1,inplace=True)
df.drop('나이',axis=1)

   이름
 b  b
c   c
d   d
e   e

In [ ]:
df.shape

(4, 2)

In [ ]:
data = {
    'name' : ['a','b','c'],
    'age' : [10,20,30],
    'salary' : [50000,60000,30000]
}
df = pd.DataFrame(data)
df.index = ['서울','대전','대구']
df

   name  age  salary
서울    a   10   50000
대전    b   20   60000
대구    c   30   30000

In [ ]:
# 행을 선택  loc(인덱스 이름 기반), iloc(위치기반)
df.loc[ : '대전']
# df.iloc[:2]

   name  age  salary
서울    a   10   50000
대전    b   20   60000

In [ ]:
# 열을 선택
df[['name','age']]  # 슬라이싱 이 안됨

   name  age
서울    a   10
대전    b   20
대구    c   30

In [ ]:
# loc iloc 행,열을 선택할수 있음
# df.loc['서울':'대전', 'name':'age']
df.iloc[0:2, 0:2]

   name  age
서울    a   10
대전    b   20

In [ ]:
# 데이터 추가
df['addr'] = ['aaa','bbb','ccc']
df

   name  age  salary addr
서울    a   10   50000  aaa
대전    b   20   60000  bbb
대구    c   30   30000  ccc

In [ ]:
# 전치 : 뒤집기 transpose  T
df_t = df.T
df_t

           서울     대전     대구
name        a      b      c
age        10     20     30
salary  50000  60000  30000
addr      aaa    bbb    ccc

In [ ]:
file_path = '/content/drive/MyDrive/data/소상공인/소상공인시장진흥공단_상가업소정보_의료기관_201909.csv'
df = pd.read_csv(file_path,encoding='cp949')
df.head(2)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19956873,하나산부인과,NaN,S,의료,S01,병원,S01B10,산부인과,Q86201,일반 의원,41.0,경기도,41273.0,안산시 단원구,4127360000,선부3동,4.127311e+09,선부동,4.130000e+18,1,대지,1081,NaN,경기도 안산시 단원구 선부동 1081,4.130000e+11,경기도 안산시 단원구 달미로,10,NaN,4.130000e+24,산호한양아파트,경기도 안산시 단원구 달미로 10,425764.0,15236.0,NaN,NaN,NaN,126.814295,37.336344
1,20024149,타워광명내과의원,NaN,S,의료,S01,병원,S01B07,내과/외과,Q86201,일반 의원,11.0,서울특별시,11680.0,강남구,1168065600,도곡2동,1.168012e+09,도곡동,1.170000e+18,1,대지,467,14.0,서울특별시 강남구 도곡동 467-14,1.170000e+11,서울특별시 강남구 언주로30길,39,NaN,1.170000e+24,NaN,서울특별시 강남구 언주로30길 39,135270.0,6292.0,NaN,4.0,NaN,127.053198,37.488742

In [ ]:
pd.options.display.max_columns = None

In [ ]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19956873,하나산부인과,NaN,S,의료,S01,병원,S01B10,산부인과,Q86201,일반 의원,41.0,경기도,41273.0,안산시 단원구,4127360000,선부3동,4.127311e+09,선부동,4.130000e+18,1,대지,1081,NaN,경기도 안산시 단원구 선부동 1081,4.130000e+11,경기도 안산시 단원구 달미로,10,NaN,4.130000e+24,산호한양아파트,경기도 안산시 단원구 달미로 10,425764.0,15236.0,NaN,NaN,NaN,126.814295,37.336344
1,20024149,타워광명내과의원,NaN,S,의료,S01,병원,S01B07,내과/외과,Q86201,일반 의원,11.0,서울특별시,11680.0,강남구,1168065600,도곡2동,1.168012e+09,도곡동,1.170000e+18,1,대지,467,14.0,서울특별시 강남구 도곡동 467-14,1.170000e+11,서울특별시 강남구 언주로30길,39,NaN,1.170000e+24,NaN,서울특별시 강남구 언주로30길 39,135270.0,6292.0,NaN,4.0,NaN,127.053198,37.488742
2,20152277,조정현신경외과의원,NaN,S,의료,S01,병원,S01B15,신경외과,Q86201,일반 의원,41.0,경기도,41390.0,시흥시,4139059100,정왕1동,4.139013e+09,정왕동,4.140000e+18,1,대지,1740,1.0,경기도 시흥시 정왕동 1740-1,4.140000e+11,경기도 시흥시 중심상가로,178,NaN,4.140000e+24,한라프라자,경기도 시흥시 중심상가로 178,429450.0,15066.0,NaN,NaN,NaN,126.734841,37.344955
3,20350610,한귀원정신과의원,NaN,S,의료,S01,병원,S01B99,기타병원,NaN,NaN,26.0,부산광역시,26500.0,수영구,2650078000,광안3동,2.650010e+09,광안동,2.650000e+18,1,대지,74,1.0,부산광역시 수영구 광안동 74-1,2.650000e+11,부산광역시 수영구 수영로,688,NaN,2.650000e+24,NaN,부산광역시 수영구 수영로 688,613100.0,48266.0,NaN,5.0,NaN,129.115438,35.166872
4,20364049,더블유스토어수지점,수지점,S,의료,S02,약국/한약방,S02A01,약국,G47811,의약품 및 의료용품 소매업,41.0,경기도,41465.0,용인시 수지구,4146551000,풍덕천1동,4.146510e+09,풍덕천동,4.150000e+18,1,대지,712,2.0,경기도 용인시 수지구 풍덕천동 712-2,4.150000e+11,경기도 용인시 수지구 문정로,32,NaN,4.150000e+24,NaN,경기도 용인시 수지구 문정로 32,448170.0,16837.0,NaN,1.0,NaN,127.095522,37.323528

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91335 entries, 0 to 91334
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상가업소번호     91335 non-null  int64
 1   상호명        91335 non-null  object
 2   지점명        1346 non-null   object
 3   상권업종대분류코드  91335 non-null  object
 4   상권업종대분류명   91335 non-null  object
 5   상권업종중분류코드  91335 non-null  object
 6   상권업종중분류명   91335 non-null  object
 7   상권업종소분류코드  91335 non-null  object
 8   상권업종소분류명   91335 non-null  object
 9   표준산업분류코드   86413 non-null  object
 10  표준산업분류명    86413 non-null  object
 11  시도코드       90956 non-null  float64
 12  시도명        90956 non-null  object
 13  시군구코드      90956 non-null  float64
 14  시군구명       90956 non-null  object
 15  행정동코드      91335 non-null  int64
 16  행정동명       90956 non-null  object
 17  법정동코드      91280 non-null  float64
 18  법정동명       91280 non-null  object
 19  지번코드       91335 non-null  float64
 20  대지구분코드     91335 non-null  int64
 21  대지구분명      91335 non-null  object
 22  지번본번지      91335 non-null  int64
 23  지번부번지      72079 non-null  float64
 24  지번주소       91335 non-null  object
 25  도로명코드      91335 non-null  float64
 26  도로명        91335 non-null  object
 27  건물본번지      91335 non-null  int64
 28  건물부번지      10604 non-null  float64
 29  건물관리번호     91335 non-null  float64
 30  건물명        46453 non-null  object
 31  도로명주소      91335 non-null  object
 32  구우편번호      91323 non-null  float64
 33  신우편번호      91333 non-null  float64
 34  동정보        7406 non-null   object
 35  층정보        43989 non-null  float64
 36  호정보        15437 non-null  float64
 37  경도         91335 non-null  float64
 38  위도         91335 non-null  float64
dtypes: float64(14), int64(5), object(20)
memory usage: 27.2+ MB

In [ ]:
# 수치형 데이터에 대해서 통계적표현
# 숫자형 데이터 리스트
df.describe().columns

Index(['상가업소번호', '시도코드', '시군구코드', '행정동코드', '법정동코드', '지번코드', '대지구분코드', '지번본번지',
       '지번부번지', '도로명코드', '건물본번지', '건물부번지', '건물관리번호', '구우편번호', '신우편번호', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [ ]:
# 범주형/문자열 데이터
df.describe(include='object')

,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,지번주소,도로명,건물명,도로명주소,동정보
count,91335,1346,91335,91335,91335,91335,91335,91335,86413,86413,90956,90956,90956,91280,91335,91335,91335,46453,91335,7406
unique,56908,858,1,1,5,5,34,34,15,15,17,228,2791,2822,2,53118,16610,17946,54031,556
top,리원,장례식장,S,의료,S01,병원,S02A01,약국,Q86201,일반 의원,경기도,서구,중앙동,중동,대지,서울특별시 동대문구 제기동 965-1,서울특별시 강남구 강남대로,현대아파트,서울특별시 동대문구 약령중앙로8길 10,1
freq,152,97,91335,91335,60774,60774,18964,18964,22555,22555,21374,3165,1856,874,91213,198,326,131,198,1571

In [ ]:
# describe를 이용한 데이터 요약표
# 수치형 데이터
# 범주형 데이터
# 결측치는 몇개
# df.isna().sum()
df.isna().mean()
# 결측치가 있는 컬럼만 추출하려면
temp = df.isna().mean()
temp[temp>0]

지점명         0.985263
표준산업분류코드    0.053890
표준산업분류명     0.053890
시도코드        0.004150
시도명         0.004150
시군구코드       0.004150
시군구명        0.004150
행정동명        0.004150
법정동코드       0.000602
법정동명        0.000602
지번부번지       0.210828
건물부번지       0.883900
건물명         0.491400
구우편번호       0.000131
신우편번호       0.000022
동정보         0.918914
층정보         0.518377
호정보         0.830985
dtype: float64

# 데이터프레임
```
info()
  1.데이터 타입 정보
  2.결측치 여부
  3.결측치가 없어도 수치형인데. 타입이 object이면. 수치형외에 다른데이터가 포함되어 있다
  4.인덱스가 정렬되어 있는지 여부
describe()  통계적 분석  4분위수 및 최대 최소 카운트
  --> 수치형 데이터
  --> 범주형 include = 'object'
        최빈값, 유니크, 빈도수
  --> 위의 두가지를 다 출력 include='all'
isna() : 결측치 여부확인
isna().sum() or isna().mean()
temp = df.isna().sum()
temp[temp>0] : 결측치가 있는 데이터의 컬럼명과 합을 시리즈로


```

# 요약표만들기

In [ ]:
# 수치형 데이터
df = pd.read_csv(file_path,encoding='cp949')
numeric_summary = df.describe()
# 범주형 데이터
categorical_summary = df.describe(include='object')
# 결측치
missing_summary = df.isna().mean()
missing_summary = missing_summary[missing_summary>0]

In [ ]:
categorical_summary

,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,지번주소,도로명,건물명,도로명주소,동정보
count,91335,1346,91335,91335,91335,91335,91335,91335,86413,86413,90956,90956,90956,91280,91335,91335,91335,46453,91335,7406
unique,56908,858,1,1,5,5,34,34,15,15,17,228,2791,2822,2,53118,16610,17946,54031,556
top,리원,장례식장,S,의료,S01,병원,S02A01,약국,Q86201,일반 의원,경기도,서구,중앙동,중동,대지,서울특별시 동대문구 제기동 965-1,서울특별시 강남구 강남대로,현대아파트,서울특별시 동대문구 약령중앙로8길 10,1
freq,152,97,91335,91335,60774,60774,18964,18964,22555,22555,21374,3165,1856,874,91213,198,326,131,198,1571

In [ ]:
numeric_summary

,상가업소번호,시도코드,시군구코드,행정동코드,법정동코드,지번코드,대지구분코드,지번본번지,지번부번지,도로명코드,건물본번지,건물부번지,건물관리번호,구우편번호,신우편번호,층정보,호정보,경도,위도
count,9.133500e+04,90956.000000,90956.000000,9.133500e+04,9.128000e+04,9.133500e+04,91335.000000,91335.000000,72079.000000,9.133500e+04,91335.000000,10604.000000,9.133500e+04,91323.000000,91333.00000,43989.000000,1.543700e+04,91335.000000,91335.000000
mean,2.121818e+07,32.586712,32898.381877,3.293232e+09,3.293385e+09,3.293350e+18,1.001336,587.534549,17.005092,3.293345e+11,251.200482,7.241135,3.295158e+24,428432.911085,28085.47698,2.649571,5.995938e+02,127.487524,36.624711
std,5.042828e+06,13.045138,12985.393171,1.297387e+09,1.297706e+09,1.297268e+18,0.036524,582.519364,53.451413,1.297263e+11,477.456487,12.426816,1.298360e+24,193292.339066,18909.01455,22.367356,1.281129e+04,0.842877,1.041361
min,2.901108e+06,11.000000,11110.000000,1.111052e+09,1.111010e+09,1.110000e+18,1.000000,1.000000,1.000000,1.110000e+11,0.000000,1.000000,1.110000e+24,100011.000000,1000.00000,-2.000000,-3.050000e+02,124.717632,33.219290
25%,2.001931e+07,26.000000,26350.000000,2.635065e+09,2.635011e+09,2.640000e+18,1.000000,162.000000,2.000000,2.640000e+11,29.000000,1.000000,2.640000e+24,302120.000000,11681.00000,1.000000,8.000000e+00,126.914297,35.811830
50%,2.211900e+07,41.000000,41117.000000,4.111758e+09,4.111710e+09,4.110000e+18,1.000000,462.000000,5.000000,4.110000e+11,92.000000,2.000000,4.110000e+24,440300.000000,24353.00000,2.000000,2.010000e+02,127.084551,37.234652
75%,2.480984e+07,43.000000,43113.000000,4.311370e+09,4.311311e+09,4.310000e+18,1.000000,858.000000,14.000000,4.310000e+11,257.000000,9.000000,4.310000e+24,602811.000000,46044.00000,3.000000,3.060000e+02,128.108919,37.507463
max,2.852470e+07,50.000000,50130.000000,5.013061e+09,5.013032e+09,5.010000e+18,2.000000,7338.000000,1428.000000,5.010000e+11,8795.000000,244.000000,5.010000e+24,799801.000000,63643.00000,4567.000000,1.162406e+06,130.909912,38.499659

In [ ]:
# 컬럼명이 달라서 옆으로 연결
summary_df =  pd.concat([numeric_summary,categorical_summary,missing_summary],axis=1)
summary_df

,상가업소번호,시도코드,시군구코드,행정동코드,법정동코드,지번코드,대지구분코드,지번본번지,지번부번지,도로명코드,건물본번지,건물부번지,건물관리번호,구우편번호,신우편번호,층정보,호정보,경도,위도,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,지번주소,도로명,건물명,도로명주소,동정보,0
count,9.133500e+04,90956.000000,90956.000000,9.133500e+04,9.128000e+04,9.133500e+04,91335.000000,91335.000000,72079.000000,9.133500e+04,91335.000000,10604.000000,9.133500e+04,91323.000000,91333.00000,43989.000000,1.543700e+04,91335.000000,91335.000000,91335,1346,91335,91335,91335,91335,91335,91335,86413,86413,90956,90956,90956,91280,91335,91335,91335,46453,91335,7406,NaN
mean,2.121818e+07,32.586712,32898.381877,3.293232e+09,3.293385e+09,3.293350e+18,1.001336,587.534549,17.005092,3.293345e+11,251.200482,7.241135,3.295158e+24,428432.911085,28085.47698,2.649571,5.995938e+02,127.487524,36.624711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5.042828e+06,13.045138,12985.393171,1.297387e+09,1.297706e+09,1.297268e+18,0.036524,582.519364,53.451413,1.297263e+11,477.456487,12.426816,1.298360e+24,193292.339066,18909.01455,22.367356,1.281129e+04,0.842877,1.041361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.901108e+06,11.000000,11110.000000,1.111052e+09,1.111010e+09,1.110000e+18,1.000000,1.000000,1.000000,1.110000e+11,0.000000,1.000000,1.110000e+24,100011.000000,1000.00000,-2.000000,-3.050000e+02,124.717632,33.219290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.001931e+07,26.000000,26350.000000,2.635065e+09,2.635011e+09,2.640000e+18,1.000000,162.000000,2.000000,2.640000e+11,29.000000,1.000000,2.640000e+24,302120.000000,11681.00000,1.000000,8.000000e+00,126.914297,35.811830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.211900e+07,41.000000,41117.000000,4.111758e+09,4.111710e+09,4.110000e+18,1.000000,462.000000,5.000000,4.110000e+11,92.000000,2.000000,4.110000e+24,440300.000000,24353.00000,2.000000,2.010000e+02,127.084551,37.234652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.480984e+07,43.000000,43113.000000,4.311370e+09,4.311311e+09,4.310000e+18,1.000000,858.000000,14.000000,4.310000e+11,257.000000,9.000000,4.310000e+24,602811.000000,46044.00000,3.000000,3.060000e+02,128.108919,37.507463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.852470e+07,50.000000,50130.000000,5.013061e+09,5.013032e+09,5.010000e+18,2.000000,7338.000000,1428.000000,5.010000e+11,8795.000000,244.000000,5.010000e+24,799801.000000,63643.00000,4567.000000,1.162406e+06,130.909912,38.499659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56908,858,1,1,5,5,34,34,15,15,17,228,2791,2822,2,53118,16610,17946,54031,556,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,리원,장례식장,S,의료,S01,병원,S02A01,약국,Q86201,일반 의원,경기도,서구,중앙동,중동,대지,서울특별시 동대문구 제기동 965-1,서울특별시 강남구 강남대로,현대아파트,서울특별시 동대문구 약령중앙로8길 10,1,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152,97,91335,91335,60774,60774,18964,18964,22555,22555,21374,3165,1856,874,91213,198,326,131,198,1571,NaN
지점명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.985263
표준산업분류코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.053890
표준산업분류명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.053890
시도코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004150
시도명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004150
시군구코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004150
시군구명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004150
행정동명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004150
법정동코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000602
법정동명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000602
지번부번지,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.210828
건물부번지,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.883900
건물명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.491400
구우편번호,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000131
신우편번호,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000022
동정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.918914
층정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.518377
호정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.830985

```
           count mean std min max unique top freq
 컬럼명1    00    nan              00
 컬럼명2    00    000                 
 컬럼명3    00
```

In [ ]:
summary_df = pd.DataFrame(index = df.columns,
             columns=['count','mean','std','min','max','unique','top','freq'])
# 각 컬럼에 대해서 통계를 채우기\
for col in df.columns:
  if df[col].dtype in ['int64','float64']: # 수치형
    desc = df[col].describe()
    summary_df.loc[col,'count'] = desc['count']
    summary_df.loc[col,'mean'] = desc['mean']
    summary_df.loc[col,'std'] = desc['std']
    summary_df.loc[col,'min'] = desc['min']
    summary_df.loc[col,'mas'] = desc['max']
  else: # 범주형
    desc = df[col].describe()
    summary_df.loc[col,'count'] = desc['count']
    summary_df.loc[col,'unique'] = desc['unique']
    summary_df.loc[col,'top'] = desc['top']
    summary_df.loc[col,'freq'] = desc['freq']
summary_df

,count,mean,std,min,max,unique,top,freq,mas
상가업소번호,91335.0,21218180.559435,5042828.147112,2901108.0,NaN,NaN,NaN,NaN,2.852470e+07
상호명,91335,NaN,NaN,NaN,NaN,56908,리원,152,NaN
지점명,1346,NaN,NaN,NaN,NaN,858,장례식장,97,NaN
상권업종대분류코드,91335,NaN,NaN,NaN,NaN,1,S,91335,NaN
상권업종대분류명,91335,NaN,NaN,NaN,NaN,1,의료,91335,NaN
상권업종중분류코드,91335,NaN,NaN,NaN,NaN,5,S01,60774,NaN
상권업종중분류명,91335,NaN,NaN,NaN,NaN,5,병원,60774,NaN
상권업종소분류코드,91335,NaN,NaN,NaN,NaN,34,S02A01,18964,NaN
상권업종소분류명,91335,NaN,NaN,NaN,NaN,34,약국,18964,NaN
표준산업분류코드,86413,NaN,NaN,NaN,NaN,15,Q86201,22555,NaN
표준산업분류명,86413,NaN,NaN,NaN,NaN,15,일반 의원,22555,NaN
시도코드,90956.0,32.586712,13.045138,11.0,NaN,NaN,NaN,NaN,5.000000e+01
시도명,90956,NaN,NaN,NaN,NaN,17,경기도,21374,NaN
시군구코드,90956.0,32898.381877,12985.393171,11110.0,NaN,NaN,NaN,NaN,5.013000e+04
시군구명,90956,NaN,NaN,NaN,NaN,228,서구,3165,NaN
행정동코드,91335.0,3293231794.611047,1297387076.549655,1111051500.0,NaN,NaN,NaN,NaN,5.013061e+09
행정동명,90956,NaN,NaN,NaN,NaN,2791,중앙동,1856,NaN
법정동코드,91280.0,3293384644.306464,1297706281.227764,1111010200.0,NaN,NaN,NaN,NaN,5.013032e+09
법정동명,91280,NaN,NaN,NaN,NaN,2822,중동,874,NaN
지번코드,91335.0,3293350303826572288.0,1297267575366664960.0,1110000000000000000.0,NaN,NaN,NaN,NaN,5.010000e+18
대지구분코드,91335.0,1.001336,0.036524,1.0,NaN,NaN,NaN,NaN,2.000000e+00
대지구분명,91335,NaN,NaN,NaN,NaN,2,대지,91213,NaN
지번본번지,91335.0,587.534549,582.519364,1.0,NaN,NaN,NaN,NaN,7.338000e+03
지번부번지,72079.0,17.005092,53.451413,1.0,NaN,NaN,NaN,NaN,1.428000e+03
지번주소,91335,NaN,NaN,NaN,NaN,53118,서울특별시 동대문구 제기동 965-1,198,NaN
도로명코드,91335.0,329334526742.212708,129726337599.690521,111000000000.0,NaN,NaN,NaN,NaN,5.010000e+11
도로명,91335,NaN,NaN,NaN,NaN,16610,서울특별시 강남구 강남대로,326,NaN
건물본번지,91335.0,251.200482,477.456487,0.0,NaN,NaN,NaN,NaN,8.795000e+03
건물부번지,10604.0,7.241135,12.426816,1.0,NaN,NaN,NaN,NaN,2.440000e+02
건물관리번호,91335.0,3295158373022389894119424.0,1298360495883843205595136.0,1109999999999999970639872.0,NaN,NaN,NaN,NaN,5.010000e+24
건물명,46453,NaN,NaN,NaN,NaN,17946,현대아파트,131,NaN
도로명주소,91335,NaN,NaN,NaN,NaN,54031,서울특별시 동대문구 약령중앙로8길 10,198,NaN
구우편번호,91323.0,428432.911085,193292.339066,100011.0,NaN,NaN,NaN,NaN,7.998010e+05
신우편번호,91333.0,28085.47698,18909.01455,1000.0,NaN,NaN,NaN,NaN,6.364300e+04
동정보,7406,NaN,NaN,NaN,NaN,556,1,1571,NaN
층정보,43989.0,2.649571,22.367356,-2.0,NaN,NaN,NaN,NaN,4.567000e+03
호정보,15437.0,599.593833,12811.28838,-305.0,NaN,NaN,NaN,NaN,1.162406e+06
경도,91335.0,127.487524,0.842877,124.717632,NaN,NaN,NaN,NaN,1.309099e+02
위도,91335.0,36.624711,1.041361,33.21929,NaN,NaN,NaN,NaN,3.849966e+01

In [ ]:
for col in df.columns:
  print(col, df[col].dtype)

상가업소번호 int64
상호명 object
지점명 object
상권업종대분류코드 object
상권업종대분류명 object
상권업종중분류코드 object
상권업종중분류명 object
상권업종소분류코드 object
상권업종소분류명 object
표준산업분류코드 object
표준산업분류명 object
시도코드 float64
시도명 object
시군구코드 float64
시군구명 object
행정동코드 int64
행정동명 object
법정동코드 float64
법정동명 object
지번코드 float64
대지구분코드 int64
대지구분명 object
지번본번지 int64
지번부번지 float64
지번주소 object
도로명코드 float64
도로명 object
건물본번지 int64
건물부번지 float64
건물관리번호 float64
건물명 object
도로명주소 object
구우편번호 float64
신우편번호 float64
동정보 object
층정보 float64
호정보 float64
경도 float64
위도 float64

# 결측치와 데이터 타입만 데이터 프레임 형태로
```
      Data_Type   Missing_count   Missing_Ratio(%)
컬럼1      
컬럼1      
컬럼1      
컬럼1      
```

In [ ]:
pd.DataFrame({
    'Data_Type': df.dtypes,
    'Missing_count': df.isna().sum(),
    'Missing_Ratio(%)': df.isna().mean()*100
}
)

          Data_Type  Missing_count  Missing_Ratio(%)
상가업소번호        int64              0          0.000000
상호명          object              0          0.000000
지점명          object          89989         98.526304
상권업종대분류코드    object              0          0.000000
상권업종대분류명     object              0          0.000000
상권업종중분류코드    object              0          0.000000
상권업종중분류명     object              0          0.000000
상권업종소분류코드    object              0          0.000000
상권업종소분류명     object              0          0.000000
표준산업분류코드     object           4922          5.388953
표준산업분류명      object           4922          5.388953
시도코드        float64            379          0.414956
시도명          object            379          0.414956
시군구코드       float64            379          0.414956
시군구명         object            379          0.414956
행정동코드         int64              0          0.000000
행정동명         object            379          0.414956
법정동코드       float64             55          0.060218
법정동명         object             55          0.060218
지번코드        float64              0          0.000000
대지구분코드        int64              0          0.000000
대지구분명        object              0          0.000000
지번본번지         int64              0          0.000000
지번부번지       float64          19256         21.082827
지번주소         object              0          0.000000
도로명코드       float64              0          0.000000
도로명          object              0          0.000000
건물본번지         int64              0          0.000000
건물부번지       float64          80731         88.389993
건물관리번호      float64              0          0.000000
건물명          object          44882         49.139979
도로명주소        object              0          0.000000
구우편번호       float64             12          0.013138
신우편번호       float64              2          0.002190
동정보          object          83929         91.891389
층정보         float64          47346         51.837740
호정보         float64          75898         83.098484
경도          float64              0          0.000000
위도          float64              0          0.000000

# PM
```
특정경로에 있는 파일들을 전부 리스트업
순환문을 통해 각각 의 csv를 DataFrame 객체화
하나의 csv 로 합침
```

In [ ]:
import os
files = os.listdir('/content/drive/MyDrive/data/소상공인')
for file in files:
  file = '/content/drive/MyDrive/data/소상공인/' + file
  try:
    with open(file, 'r') as f:
      print(file,'파일')
  except:
    print(file,'디렉터리')

/content/drive/MyDrive/data/소상공인/소상공인시장진흥공단_상가업소정보_의료기관_201909.csv 파일
/content/drive/MyDrive/data/소상공인/sub1 디렉터리

In [ ]:
from glob import glob
from tqdm import tqdm  # 진행형황
files = glob('/content/drive/MyDrive/data/소상공인/sub1/*.csv')
files[0]

'/content/drive/MyDrive/data/소상공인/sub1/소상공인시장진흥공단_상가(상권)정보_제주_202412.csv'

In [ ]:
df = pd.read_csv(files[0])
# 상가업소번호와 코드가 들어간 명칭은 제외
new_cols = [col for col in df.columns if '코드' not in col]
new_cols = new_cols[1:11] + new_cols[-2:]
new_df = df[new_cols]
new_df.head(1)

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,경도,위도
0,유남회센타,NaN,소매,식료품 소매,건어물/젓갈 소매업,건어물 및 젓갈류 소매업,제주특별자치도,제주시,이도1동,이도일동,126.52558,33.512765

In [ ]:
total_dfs = []
for file in tqdm(files):
  df = pd.read_csv(file,low_memory=False)
  # 상가업소번호와 코드가 들어간 명칭은 제외
  new_cols = [col for col in df.columns if '코드' not in col]
  new_cols = new_cols[1:11] + new_cols[-2:]
  new_df = df[new_cols]
  total_dfs.append(new_df)

# 리스트에 담기 데이터프레임들을 열(column) 기준으로 합친다  axis=1
merged_df = pd.concat(total_dfs,axis=0)

100%|██████████| 17/17 [00:58<00:00,  3.43s/it]

In [ ]:
merged_df.shape

(2792840, 12)

In [ ]:
merged_df.head(2)

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,경도,위도
0,유남회센타,NaN,소매,식료품 소매,건어물/젓갈 소매업,건어물 및 젓갈류 소매업,제주특별자치도,제주시,이도1동,이도일동,126.525580,33.512765
1,서울아산정형외과,NaN,보건의료,의원,내과/소아과 의원,일반의원,제주특별자치도,제주시,조천읍,조천읍,126.667457,33.541537

In [ ]:
# 1. 데이터 기본 요약
# 데이터 의 크기 shape
print(f'데이터 크기 : {merged_df.shape}')
# 총 상점 수
print(f'총 상점 수 : {len(merged_df)}')
# 컬럼별 데이터 타입 dtype  # 컬럼별 결측치 개수
pd.DataFrame((merged_df.dtypes,merged_df.isna().sum()),index=['dtype','missing_count']).T

데이터 크기 : (2792840, 12)
총 상점 수 : 2792840

            dtype missing_count
상호명        object             1
지점명        object       2541750
상권업종대분류명   object             0
상권업종중분류명   object             0
상권업종소분류명   object             0
표준산업분류명    object           832
시도명        object             0
시군구명       object             0
행정동명       object             0
법정동명       object             0
경도        float64             0
위도        float64             0

상호명이 없는 데이터는 어떤 데이터?

In [ ]:
merged_df[merged_df['상호명'].isna()]

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,경도,위도
8878,NaN,NaN,소매,섬유·의복·신발 소매,신발 소매업,신발 소매업,부산광역시,부산진구,부전2동,부전동,129.059138,35.155237

In [ ]:
merged_df = merged_df[~merged_df['상호명'].isna()]

In [ ]:
# 1. 데이터 기본 요약
# 데이터 의 크기 shape
print(f'데이터 크기 : {merged_df.shape}')
# 총 상점 수
print(f'총 상점 수 : {len(merged_df)}')
# 컬럼별 데이터 타입 dtype  # 컬럼별 결측치 개수
pd.DataFrame((merged_df.dtypes,merged_df.isna().sum()),index=['dtype','missing_count']).T

데이터 크기 : (2792839, 12)
총 상점 수 : 2792839

            dtype missing_count
상호명        object             0
지점명        object       2541749
상권업종대분류명   object             0
상권업종중분류명   object             0
상권업종소분류명   object             0
표준산업분류명    object           832
시도명        object             0
시군구명       object             0
행정동명       object             0
법정동명       object             0
경도        float64             0
위도        float64             0

In [ ]:
merged_df['시도명'].value_counts()  # 기본으로 정렬 내림차순

시도명
경기도        672885
서울특별시      553535
경상남도       176942
부산광역시      161439
경상북도       147012
인천광역시      138166
충청남도       125116
대구광역시      119621
강원특별자치도    111392
전라남도       102544
전북특별자치도     99935
충청북도        94587
대전광역시       80589
광주광역시       78148
제주특별자치도     59745
울산광역시       55885
세종특별자치시     15298
Name: count, dtype: int64

In [ ]:
# 시도별 시군구명 분포
# pd.crosstab(merged_df['시도명'],merged_df['시군구명'])
# 시군구명별 상권업종대분류명 분포
pd.crosstab(merged_df['시군구명'],merged_df['상권업종대분류명'])

상권업종대분류명  과학·기술    교육  보건의료   부동산     소매  수리·개인    숙박  시설관리·임대  예술·스포츠     음식
시군구명
가평군         293   231    64   197   1318    381  1765      164     242   1937
강남구       19122  6182  3061  3694  10546   4846   511     3155    1812  13057
강동구        1706  1871   833  1195   4373   2381   246      746     883   5248
강릉시         837  1092   277   344   3890   1867  1384      579     629   6039
강북구        1025   812   485   568   3095   1788   185      460     665   3964
...         ...   ...   ...   ...    ...    ...   ...      ...     ...    ...
홍천군         216   187    65   134   1346    436   646      198     154   1659
화성시        4700  4331   932  2615   9600   5170   442     1943    2066  13203
화순군         248   101    31    89    776    350    96      104      94   1098
화천군          58    77    13    24    429    143   229       37      59    614
횡성군         171   125    36   125    830    268   272      118      93   1085

[230 rows x 10 columns]

In [ ]:
# 두개 이상의 범주형 변수간의 교차표(빈도표)
# normalize= 비율로 전환
round(pd.crosstab(merged_df['시도명'],merged_df['상권업종대분류명'],normalize='index'),2)

상권업종대분류명  과학·기술    교육  보건의료   부동산    소매  수리·개인    숙박  시설관리·임대  예술·스포츠    음식
시도명
강원특별자치도    0.05  0.06  0.02  0.02  0.25   0.11  0.08     0.04    0.04  0.35
경기도        0.11  0.08  0.03  0.05  0.23   0.12  0.02     0.04    0.05  0.28
경상남도       0.06  0.04  0.01  0.03  0.25   0.13  0.04     0.03    0.04  0.37
경상북도       0.05  0.04  0.01  0.03  0.27   0.13  0.04     0.04    0.04  0.37
광주광역시      0.10  0.05  0.01  0.05  0.26   0.14  0.01     0.04    0.05  0.30
대구광역시      0.08  0.06  0.01  0.03  0.26   0.13  0.01     0.03    0.04  0.33
대전광역시      0.09  0.06  0.02  0.03  0.26   0.13  0.01     0.04    0.05  0.31
부산광역시      0.08  0.05  0.01  0.04  0.25   0.13  0.02     0.04    0.04  0.35
서울특별시      0.17  0.08  0.03  0.05  0.21   0.10  0.01     0.04    0.04  0.26
세종특별자치시    0.09  0.10  0.02  0.06  0.20   0.10  0.01     0.04    0.05  0.34
울산광역시      0.06  0.05  0.01  0.03  0.24   0.14  0.02     0.04    0.05  0.37
인천광역시      0.08  0.07  0.03  0.04  0.24   0.12  0.02     0.04    0.05  0.31
전라남도       0.06  0.03  0.01  0.02  0.28   0.12  0.05     0.04    0.04  0.35
전북특별자치도    0.07  0.05  0.01  0.03  0.29   0.13  0.03     0.04    0.04  0.32
제주특별자치도    0.07  0.05  0.01  0.03  0.21   0.09  0.12     0.05    0.03  0.34
충청남도       0.06  0.05  0.02  0.03  0.27   0.12  0.04     0.04    0.04  0.33
충청북도       0.06  0.06  0.02  0.03  0.26   0.12  0.03     0.04    0.05  0.34

In [ ]:
0.05	+0.06+	0.02+	0.02+	0.25+	0.11+	0.08+	0.04+	0.04+	0.35

1.02

# 업종별 통계

In [ ]:
# 업종별 대분류 상점수
# 업종별 중분류 상점수
# 중분류별 시도명 분포
print('업종별 대분류 상점수 ----------------------')
print(merged_df['상권업종대분류명'].value_counts())
print('업종별 중분류 상점수 ----------------------')
print(merged_df['상권업종중분류명'].value_counts())
print('중분류별 시도명 분포 ----------------------')
pd.crosstab(merged_df['상권업종중분류명'],merged_df['시도명'])

업종별 대분류 상점수 ----------------------
상권업종대분류명
음식         869601
소매         676615
수리·개인      325909
과학·기술      273277
교육         182519
예술·스포츠     115834
시설관리·임대    112611
부동산        107069
숙박          71871
보건의료        57533
Name: count, dtype: int64
업종별 중분류 상점수 ----------------------
상권업종중분류명
한식             369508
이용·미용          182770
기타 간이          169022
섬유·의복·신발 소매    142445
비알코올           126422
                ...
모터사이클 소매         2135
조경·유지            1786
통신장비 수리          1538
시장 조사            1398
기타 외국              56
Name: count, Length: 75, dtype: int64
중분류별 시도명 분포 ----------------------

시도명,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
상권업종중분류명,,,,,,,,,,,,,,,,,
가구 소매,365,3093,791,598,364,569,354,653,1433,52,201,468,427,541,238,430,403
가전·통신 소매,1191,8102,2359,2006,1365,1843,1247,2107,6655,144,773,1912,1417,1573,548,1536,1251
가전제품 수리,490,3193,753,589,339,590,409,633,1895,36,214,639,468,478,181,553,351
가정용품 대여,656,2209,478,413,239,393,283,434,1624,55,130,371,246,438,374,403,243
고용 알선,699,5167,1209,1093,535,782,498,919,3919,89,404,985,702,666,192,1468,1059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
청소·방제,976,7840,1440,1250,707,986,1011,1307,4800,171,605,1527,886,857,523,1212,1000
컴퓨터 수리,173,2228,422,313,193,362,249,533,1755,46,160,441,180,188,62,228,241
통신장비 수리,39,416,71,54,48,73,52,104,333,8,21,91,41,46,24,75,42
한식,19266,77819,30234,26079,9228,16741,10633,22978,52733,2135,9204,17583,16982,14022,9073,19689,15109
회계·세무,225,3672,574,285,411,690,358,1179,6883,69,221,679,173,360,170,357,241

# group by

In [ ]:
merged_df.groupby(['시도명','상권업종대분류명']).size().unstack(fill_value=0)

상권업종대분류명,과학·기술,교육,보건의료,부동산,소매,수리·개인,숙박,시설관리·임대,예술·스포츠,음식
시도명,,,,,,,,,,
강원특별자치도,5757,6226,1830,2525,27514,11764,8376,4195,4274,38931
경기도,72241,57098,17476,30795,156125,79053,10447,28217,30389,191044
경상남도,9934,7867,1413,5830,44138,22649,6620,5923,6660,65908
경상북도,7757,5744,939,4048,39046,18463,6336,5191,5619,53869
광주광역시,7469,4119,1093,3684,20018,11013,792,3042,3576,23342
대구광역시,9692,6761,1486,4157,31475,16003,1041,4053,5116,39837
대전광역시,6878,5209,1930,2557,20857,10690,721,3208,3701,24838
부산광역시,13250,7736,2304,6046,40480,20868,2646,5778,6159,56172
서울특별시,94499,44525,18743,25189,118697,53048,8246,24801,20902,144885
세종특별자치시,1329,1574,234,866,3071,1557,111,649,738,5169
울산광역시,3494,3006,525,1911,13166,7704,1018,2015,2604,20442
인천광역시,11223,9938,3713,5628,32683,16769,3229,5297,6892,42794
전라남도,5855,3560,763,2206,28750,12418,4858,4001,3819,36314
전북특별자치도,6646,4531,868,3163,29415,12730,3022,3799,4009,31752
제주특별자치도,4096,2905,370,1870,12717,5180,7248,3095,1931,20333
충청남도,7611,6454,2180,3750,33805,14519,4695,5278,5176,41648
충청북도,5546,5266,1666,2844,24658,11481,2465,4069,4269,32323

In [ ]:
merged_df.groupby(['시도명','상권업종대분류명'])['상권업종대분류명'].count()

시도명      상권업종대분류명
강원특별자치도  과학·기술        5757
         교육           6226
         보건의료         1830
         부동산          2525
         소매          27514
                     ...
충청북도     수리·개인       11481
         숙박           2465
         시설관리·임대      4069
         예술·스포츠       4269
         음식          32323
Name: 상권업종대분류명, Length: 170, dtype: int64

In [ ]:
merged_df.groupby('시도명')['상권업종중분류명'].count()

시도명
강원특별자치도    111392
경기도        672885
경상남도       176942
경상북도       147012
광주광역시       78148
대구광역시      119621
대전광역시       80589
부산광역시      161439
서울특별시      553535
세종특별자치시     15298
울산광역시       55885
인천광역시      138166
전라남도       102544
전북특별자치도     99935
제주특별자치도     59745
충청남도       125116
충청북도        94587
Name: 상권업종중분류명, dtype: int64

In [ ]:
# 각각의 컬럼에 서로다른 통계함수를 적용한다면
merged_df.groupby('시도명').agg({'상권업종중분류명':'count','상호명':'nunique'})

         상권업종중분류명     상호명
시도명
강원특별자치도    111392   96783
경기도        672885  505849
경상남도       176942  144393
경상북도       147012  122160
광주광역시       78148   66061
대구광역시      119621   99165
대전광역시       80589   67333
부산광역시      161439  129687
서울특별시      553535  432889
세종특별자치시     15298   14358
울산광역시       55885   48304
인천광역시      138166  114868
전라남도       102544   87159
전북특별자치도     99935   86149
제주특별자치도     59745   55288
충청남도       125116  106201
충청북도        94587   81264

In [ ]:
merged_df.groupby('시도명').agg({'위도':['mean','std'],'경도':'mean'}).round(2)

            위도            경도
          mean   std    mean
시도명
강원특별자치도  37.69  0.32  128.31
경기도      37.43  0.22  127.01
경상남도     35.20  0.19  128.54
경상북도     36.16  0.34  128.83
광주광역시    35.16  0.03  126.87
대구광역시    35.86  0.06  128.58
대전광역시    36.35  0.03  127.39
부산광역시    35.17  0.05  129.06
서울특별시    37.54  0.05  126.99
세종특별자치시  36.53  0.06  127.27
울산광역시    35.54  0.05  129.32
인천광역시    37.49  0.08  126.66
전라남도     34.86  0.22  127.05
전북특별자치도  35.81  0.16  127.02
제주특별자치도  33.43  0.11  126.52
충청남도     36.65  0.25  126.92
충청북도     36.76  0.23  127.65

# 위경도를 알면 상점간의 거리를 알수 있다

In [ ]:
# 2D 형태... n행 x 2열
# 출력  (n, 2) 크기의 배열  n은 상점수
# n = 3
# [[000,000],
#  [000,000]
#  [000,000]]
import numpy as np
coords = df[['경도','위도']].to_numpy()
print(coords.shape)
# 차원 확장  (n, 2) --> (n,1,2)  (3,2) --> (3,1,2)
coords2 = np.expand_dims(coords,axis=1)
print(coords2.shape)  # (553535, 1, 2)
# (553535, 1, 2) 배열과 (553535,  2) 간의 차이를 계산  모든 상점 쌍간의 좌표 차이를 구함
# (n,n,2)  -->(경도차이, 위도차이)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
import numpy as np
from glob import glob
from tqdm import tqdm  # 진행형황
files = glob('/content/drive/MyDrive/data/소상공인/sub1/*.csv')
files[6]
df = pd.read_csv(files[6])

In [ ]:
# 표준 편차 : 각 값들이  평균으로부터 얼마나 떨어져 있는지 나타내는 지표
summary_status =  df.groupby(['시군구명']).agg({
    '상호명' : 'count',  # 상점 수
    '경도' : ['mean','std'],
    '위도' : ['mean','std']
}).round(2)
summary_status.columns = ['상점 수','평균_경도','경도_표준편차','평균_위도','위도_표준편차']
for category in ['음식','소매']:
  summary_status[f'{category} 업종비율 (%)']  = \
    (df[df['상권업종대분류명'] == category].groupby('시군구명').size() / summary_status['상점 수'] * 100).round(2)

summary_status

       상점 수   평균_경도  경도_표준편차  평균_위도  위도_표준편차  음식 업종비율 (%)  소매 업종비율 (%)
시군구명
강릉시   16938  128.89     0.04  37.78     0.05        35.65        22.97
고성군    2574  128.50     0.05  38.35     0.08        34.58        22.88
동해시    6140  129.11     0.01  37.52     0.03        36.86        26.92
삼척시    4352  129.18     0.08  37.37     0.10        39.25        24.66
속초시    7484  128.58     0.02  38.20     0.01        40.39        25.47
양구군    1495  128.00     0.04  38.12     0.05        36.32        24.82
양양군    3084  128.65     0.07  38.06     0.06        32.78        20.75
영월군    2799  128.44     0.12  37.20     0.05        31.62        26.80
원주시   22934  127.94     0.05  37.34     0.03        32.98        24.91
인제군    2920  128.23     0.09  38.07     0.09        33.77        27.26
정선군    3026  128.75     0.09  37.32     0.10        35.56        28.92
철원군    2998  127.30     0.09  38.20     0.03        36.42        27.15
춘천시   18043  127.73     0.04  37.87     0.03        33.90        22.88
태백시    2850  128.99     0.02  37.16     0.03        35.72        29.47
평창군    3908  128.49     0.14  37.57     0.11        34.80        22.29
홍천군    5041  127.89     0.16  37.70     0.05        32.91        26.70
화천군    1683  127.65     0.10  38.10     0.04        36.48        25.49
횡성군    3123  128.05     0.10  37.49     0.04        34.74        26.58

In [ ]:
df['상권업종대분류명'].value_counts()

상권업종대분류명
음식         38931
소매         27514
수리·개인      11764
숙박          8376
교육          6226
과학·기술       5757
예술·스포츠      4274
시설관리·임대     4195
부동산         2525
보건의료        1830
Name: count, dtype: int64

In [ ]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 타이타닉 데이터에서 생존에 미치는 영향을 분석..
# 불필요한 컬럼을 제거
# 탐색 (데이터 정보 info, 열이름 columns, 기본통계량 describe)
# 결측치 값을 확인
# 중복데이터 확인 df.duplicated()  -- true false

In [ ]:
removed_cols = ['PassengerId','Name','Ticket'	,'Fare'	,'Cabin'	,'Embarked']
df = df.drop(removed_cols,axis=1)

In [ ]:
df.rename(columns={'Sex':'Gender'},inplace=True)

In [ ]:
print(f'데이터 정보 : {df.info()}')
print(f'열 이름 : {df.columns}')
print(f'기본통계량 수치형 : {df.describe()}')
print(f"기본통계량 범주형 : {df.describe(include = 'object')}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Gender    891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
dtypes: float64(1), int64(4), object(1)
memory usage: 41.9+ KB
데이터 정보 : None
열 이름 : Index(['Survived', 'Pclass', 'Gender', 'Age', 'SibSp', 'Parch'], dtype='object')
기본통계량 수치형 :          Survived      Pclass         Age       SibSp       Parch
count  891.000000  891.000000  714.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594
std      0.486592    0.836071   14.526497    1.102743    0.806057
min      0.000000    1.000000    0.420000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000
50%      0.000000    3.000000   28.000000    0.000000    0.000000
75%      1.000000    3.000000   38.000000    1.000000    0.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000
기본통계량 범주형 :        Gender
count     891
unique      2
top      male
freq      577

In [ ]:
# 결측치 확인
df.isna().mean()

Survived    0.000000
Pclass      0.000000
Gender      0.000000
Age         0.198653
SibSp       0.000000
Parch       0.000000
dtype: float64

In [ ]:
# 중복데이터
df[df.duplicated()]

     Survived  Pclass  Gender   Age  SibSp  Parch
26          0       3    male   NaN      0      0
28          1       3  female   NaN      0      0
29          0       3    male   NaN      0      0
32          1       3  female   NaN      0      0
42          0       3    male   NaN      0      0
..        ...     ...     ...   ...    ...    ...
882         0       3  female  22.0      0      0
883         0       2    male  28.0      0      0
884         0       3    male  25.0      0      0
886         0       2    male  27.0      0      0
890         0       3    male  32.0      0      0

[364 rows x 6 columns]